version: '3'

services:
  health:
    image: lambci/lambda:nodejs12.x
    ports:
      - "9001:9001"
    volumes:
      - .:/var/task:ro,delegated
    command: dist/health.handler
    # env_file: ./.env
    environment: 
      - DOCKER_LAMBDA_STAY_OPEN=1
      - DOCKER_LAMBDA_WATCH=1
      - AWS_LAMBDA_FUNCTION_NAME=handler # Needed by some libraries that expect this to be already set
